name: todo_riverpod
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.13.1
  auto_route: ^8.0.3
  get_storage: ^2.1.1
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  lottie: ^3.1.0
  iconsax: ^0.0.8
  google_sign_in: ^6.2.1
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/logos/
